development:
  secret_key_base: sk_test_51Iv8oiE53p3m88NxNbSBrH86tFynLYcCf5jt2bp7fKAMrjByVu5uT5oeAcAtnkdc10Y8M13I9P72eeWO4S51lqa000XHX5jFxL
  # Paste output of $ rake secret here for your dev machine.

test:
  secret_key_base: sk_test_51Iv8oiE53p3m88NxNbSBrH86tFynLYcCf5jt2bp7fKAMrjByVu5uT5oeAcAtnkdc10Y8M13I9P72eeWO4S51lqa000XHX5jFxL

production:
secret_key_base: sk_test_51Iv8oiE53p3m88NxNbSBrH86tFynLYcCf5jt2bp7fKAMrjByVu5uT5oeAcAtnkdc10Y8M13I9P72eeWO4S51lqa000XHX5jFxL

STRIPE_PUBLISHABLE_KEY: pk_test_51Iv8oiE53p3m88Nx7BhOANnllhtgn5YiUJHfoy8pcGs8oxOcUxqg1NutWcEyjJtZcqIbHga3gyXncu1LexC4cBSi00jENVvWN0
STRIPE_SECRET_KEY: sk_test_51Iv8oiE53p3m88NxNbSBrH86tFynLYcCf5jt2bp7fKAMrjByVu5uT5oeAcAtnkdc10Y8M13I9P72eeWO4S51lqa000XHX5jFxL